# Generated by Django 6.1.1 on 2026-09-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
    ]
